version: 0.2

phases:
  install:
    commands:
      - echo install Node..
      - curl -fsSL https://deb.nodesource.com/setup_16.x | bash -
      - apt install -y nodejs
      - echo install npm..
      - apt install nodejs
  pre_build:
    commands:
      - echo install dependencies..
      - npm install
  build:
    commands:
      - echo Testing...
      - echo Building...
      - npm run build
artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: build
